import type { Theme } from "../types/memorymatch";

// Games card
export const games = [
  {
    id: 1,
    name: "Tic-Tac-Toe",
    description: "Challenge a friend or the computer in this classic game",
    icon: "❌⭕",
    color: "from-pink-500 to-pink-700",
    btnColor: "from-pink-400 to-pink-600",
    link: "/tic-tac-toe",
  },
  {
    id: 2,
    name: "Rock-Paper-Scissors",
    description: "Play the ultimate game of chance and strategy",
    icon: "🤜🤛",
    color: "from-indigo-500 to-indigo-700",
    btnColor: "from-indigo-400 to-indigo-600",
    link: "/rock-paper-scissors",
  },
  {
    id: 3,
    name: "Memory Match",
    description: "Test your memory with this classic card matching game",
    icon: "🧠",
    color: "from-blue-500 to-blue-700",
    btnColor: "from-blue-400 to-blue-600",
    link: "/memory-match",
  },
  {
    id: 4,
    name: "Word Search",
    description: "Find hidden words in a grid of letters",
    icon: "🔍",
    color: "from-purple-500 to-purple-700",
    btnColor: "from-purple-400 to-purple-600",
    link: "/word-search",
  },
  {
    id: 5,
    name: "Puzzle Game",
    description: "Solve challenging puzzles and brain teasers",
    icon: "🧩",
    color: "from-yellow-500 to-yellow-700",
    btnColor: "from-yellow-400 to-yellow-600",
    link: "/puzzle-game",
  },
  {
    id: 6,
    name: "Sudoku",
    description: "Classic number placement puzzle",
    icon: "🔢",
    color: "from-red-500 to-red-700",
    btnColor: "from-red-400 to-red-600",
    link: "/sudoku",
  },
];

// Tic-Tac-Toe
export const ticTacToeWinningCombinations = [
  [0, 1, 2],
  [3, 4, 5],
  [6, 7, 8], // Rows
  [0, 3, 6],
  [1, 4, 7],
  [2, 5, 8], // Columns
  [0, 4, 8],
  [2, 4, 6], // Diagonals
];

// Memory Match
export const themeEmojis: Record<Theme, string[]> = {
  numbers: [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
  ],
  animals: [
    "🐶",
    "🐱",
    "🐭",
    "🐹",
    "🐰",
    "🦊",
    "🐻",
    "🐼",
    "🦁",
    "🐮",
    "🐷",
    "🐸",
    "🐵",
    "🐔",
    "🐧",
    "🐦",
    "🐤",
    "🦆",
    "🦅",
    "🦉",
    "🦇",
    "🐺",
    "🐗",
    "🐴",
    "🦄",
    "🐝",
    "🐛",
    "🦋",
  ],
  fruits: [
    "🍎",
    "🍐",
    "🍊",
    "🍋",
    "🍌",
    "🍉",
    "🍇",
    "🍓",
    "🫐",
    "🍒",
    "🍑",
    "🥭",
    "🍍",
    "🥝",
    "🍅",
    "🥥",
    "🥑",
    "🍆",
    "🥔",
    "🥕",
    "🌽",
    "🌶️",
    "🥒",
    "🥬",
    "🥦",
    "🍄",
    "🥜",
    "🌰",
  ],
};
